# -*- coding: utf-8 -*-
"""prototype_healthy_with_seg

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18WAZexwaTunEfuEBCkGBeY8qW3mFPyIH
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install rfdetr==1.5.2
!pip install timm

import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

ZIP_PATH = "/content/drive/MyDrive/dataset/plantvillage_two_folder_healthy_disease.zip"

# نسخ إلى /content
!cp "$ZIP_PATH" /content/

# فك الضغط
!unzip -q /content/plantvillage_two_folder_healthy_disease.zip -d /content/

!ls /content/plantvillage_two_folder_healthy_disease

import os
import re
import json
import numpy as np
from PIL import Image

import torch
import torch.nn as nn
from torchvision import transforms
from torchvision.models import efficientnet_b0, EfficientNet_B0_Weights
import timm

from rfdetr import RFDETRSegNano


# =========================================================
# 1) CONFIG
# =========================================================
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# فولدر الصور الصحية فقط بعد فك الضغط
HEALTHY_ROOT = "/content/plantvillage_two_folder_healthy_disease/healthy"

# موديل segmentation للورقة
LEAF_SEG_MODEL_PATH = "/content/drive/MyDrive/MARIAM_PLANET/train/RF_DETR/Leave_big_nano/checkpoint_best_total.pth"

# موديل التصنيف المحفوظ (state_dict فقط)
CLS_MODEL_PATH = "/content/drive/MyDrive/master_models/classification_healthy_disease/Result_classification_healthy_disease/best_weight_model.pth"

# فولدر الحفظ النهائي
SAVE_DIR = "/content/drive/MyDrive/master_models/prototype_healthy__with_seg/prototype_healthy_features"
os.makedirs(SAVE_DIR, exist_ok=True)

# بارامترات الـ segmentation
SEG_THRESHOLD = 0.2
SEG_IOU_THRESHOLD = 0.5

# إذا True سيتم عمل crop للورقة بعد تطبيق الماسك
USE_BBOX_CROP = True

# Normalize لكل feature vector قبل حساب الـ mean
NORMALIZE_EACH_FEATURE = True

# Normalize للـ prototype النهائي
NORMALIZE_FINAL_PROTOTYPE = True


# =========================================================
# 2) MODEL DEFINITION
# =========================================================
class EffB0_SwinTiny_Fusion(nn.Module):
    def __init__(self, num_classes: int, eff_weights):
        super().__init__()

        # EfficientNet branch
        eff = efficientnet_b0(weights=eff_weights)
        self.eff_features = eff.features
        self.eff_pool = eff.avgpool
        self.eff_out_dim = eff.classifier[1].in_features

        # Swin branch
        self.swin = timm.create_model(
            "swin_tiny_patch4_window7_224",
            pretrained=True,
            num_classes=0
        )
        self.swin_out_dim = self.swin.num_features

        # Classifier (لن نستخدمه فعليًا في prototype extraction)
        fusion_dim = self.eff_out_dim + self.swin_out_dim
        self.classifier = nn.Linear(fusion_dim, num_classes)

    def forward(self, x):
        fe = self.eff_features(x)
        fe = self.eff_pool(fe)
        fe = torch.flatten(fe, 1)

        fs = self.swin(x)

        emb = torch.cat([fe, fs], dim=1)
        logits = self.classifier(emb)
        return logits, emb


# =========================================================
# 3) HELPERS
# =========================================================
def is_image_file(filename):
    return filename.lower().endswith(
        (".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff", ".webp")
    )

def clean_plant_name(folder_name: str) -> str:
    """
    Apple___healthy -> Apple
    Corn_(maize)___healthy -> Corn_(maize)
    """
    name = folder_name.strip()
    name = re.sub(r'___healthy$', '', name, flags=re.IGNORECASE)
    name = re.sub(r'_healthy$', '', name, flags=re.IGNORECASE)
    name = re.sub(r'\s+healthy$', '', name, flags=re.IGNORECASE)
    return name.strip()

def safe_name(name: str) -> str:
    name = name.strip()
    name = name.replace("/", "_")
    name = name.replace("\\", "_")
    return name

def l2_normalize(vec, eps=1e-12):
    norm = np.linalg.norm(vec)
    if norm < eps:
        return vec
    return vec / norm

def get_bbox_from_mask(mask_bool):
    ys, xs = np.where(mask_bool)
    if len(xs) == 0 or len(ys) == 0:
        return None
    x1, x2 = xs.min(), xs.max()
    y1, y2 = ys.min(), ys.max()
    return x1, y1, x2, y2

def apply_mask_black_background(img_np, mask_bool):
    out = np.zeros_like(img_np)
    out[mask_bool] = img_np[mask_bool]
    return out

def crop_to_mask_bbox(img_np, mask_bool):
    bbox = get_bbox_from_mask(mask_bool)
    if bbox is None:
        return img_np
    x1, y1, x2, y2 = bbox
    return img_np[y1:y2+1, x1:x2+1]


# =========================================================
# 4) LOAD MODELS
# =========================================================
def load_leaf_segmentation_model(model_path):
    model = RFDETRSegNano(
        pretrain_weights=model_path,
        device=DEVICE,
        num_classes=1
    )
    model.optimize_for_inference(compile=False)
    return model


def load_classification_model(ckpt_path):
    """
    نحتاج فقط الـ emb
    ولا نحتاج classifier
    """
    checkpoint = torch.load(ckpt_path, map_location=DEVICE)

    weights = EfficientNet_B0_Weights.DEFAULT
    img_size = 224

    model = EffB0_SwinTiny_Fusion(
        num_classes=1,
        eff_weights=weights
    ).to(DEVICE)

    if isinstance(checkpoint, dict) and "model_state_dict" in checkpoint:
        state_dict = checkpoint["model_state_dict"]
        img_size = checkpoint.get("img_size", 224)
    else:
        state_dict = checkpoint

    filtered_state_dict = {}
    for k, v in state_dict.items():
        if not k.startswith("classifier."):
            filtered_state_dict[k] = v

    load_result = model.load_state_dict(filtered_state_dict, strict=False)

    print("[Classification] Model loaded for feature extraction.")
    print("[Classification] classifier layer ignored.")
    print("[Classification] Missing keys:", load_result.missing_keys)
    print("[Classification] Unexpected keys:", load_result.unexpected_keys)

    model.eval()

    eval_tf = transforms.Compose([
        transforms.Resize((img_size, img_size)),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=weights.transforms().mean,
            std=weights.transforms().std
        ),
    ])

    return model, eval_tf, img_size


# =========================================================
# 5) SEGMENT LEAF
# =========================================================
def segment_leaf(seg_model, image_pil):
    img_np = np.array(image_pil.convert("RGB"))

    detections = seg_model.predict(
        image_pil,
        threshold=SEG_THRESHOLD,
        iou_threshold=SEG_IOU_THRESHOLD
    )

    mask_combined = np.zeros(img_np.shape[:2], dtype=bool)

    if detections.mask is not None and len(detections.mask) > 0:
        for i in range(len(detections.mask)):
            mask_combined = np.logical_or(mask_combined, detections.mask[i])

    if not mask_combined.any():
        return None, False

    masked_np = apply_mask_black_background(img_np, mask_combined)

    if USE_BBOX_CROP:
        masked_np = crop_to_mask_bbox(masked_np, mask_combined)

    segmented_pil = Image.fromarray(masked_np.astype(np.uint8))
    return segmented_pil, True


# =========================================================
# 6) EXTRACT FEATURE EMBEDDING
# =========================================================
@torch.no_grad()
def extract_embedding(cls_model, transform, image_pil):
    x = transform(image_pil).unsqueeze(0).to(DEVICE)
    _, emb = cls_model(x)
    emb = emb.squeeze(0).detach().cpu().numpy().astype(np.float32)
    return emb


# =========================================================
# 7) PROCESS ONE PLANT ONLY
# =========================================================
def process_single_plant_folder(folder_path, plant_name, seg_model, cls_model, cls_tf):
    image_files = [f for f in os.listdir(folder_path) if is_image_file(f)]
    image_files = sorted(image_files)

    all_features = []
    failed_images = []

    print(f"\nProcessing plant: {plant_name}")
    print(f"Total healthy images found: {len(image_files)}")

    for idx, fname in enumerate(image_files, start=1):
        if idx % 50 == 0 or idx == 1:
            print(f"[{plant_name}] Processing {idx}/{len(image_files)}")

        img_path = os.path.join(folder_path, fname)

        try:
            img_pil = Image.open(img_path).convert("RGB")

            # 1) segmentation first
            segmented_pil, seg_success = segment_leaf(seg_model, img_pil)

            # إذا فشل segmentation نتجاوز الصورة
            if not seg_success:
                failed_images.append({
                    "image": img_path,
                    "reason": "segmentation_failed"
                })
                continue

            # 2) extract embedding لهذه الصورة فقط
            emb = extract_embedding(cls_model, cls_tf, segmented_pil)

            if NORMALIZE_EACH_FEATURE:
                emb = l2_normalize(emb).astype(np.float32)

            # 3) نخزن feature الخاصة بهذا النبات فقط
            all_features.append(emb)

        except Exception as e:
            failed_images.append({
                "image": img_path,
                "reason": str(e)
            })

    if len(all_features) == 0:
        return None, None, failed_images

    # features الخاصة بهذا النبات فقط
    all_features = np.stack(all_features, axis=0).astype(np.float32)

    # prototype لهذا النبات فقط
    prototype = all_features.mean(axis=0).astype(np.float32)

    if NORMALIZE_FINAL_PROTOTYPE:
        prototype = l2_normalize(prototype).astype(np.float32)

    return all_features, prototype, failed_images


# =========================================================
# 8) MAIN FUNCTION
# =========================================================
def build_prototypes_per_plant():
    print(f"Using device: {DEVICE}")

    print("Loading leaf segmentation model...")
    seg_model = load_leaf_segmentation_model(LEAF_SEG_MODEL_PATH)

    print("Loading classification model...")
    cls_model, cls_tf, img_size = load_classification_model(CLS_MODEL_PATH)

    print(f"Classification input size: {img_size}")

    folders = [
        d for d in os.listdir(HEALTHY_ROOT)
        if os.path.isdir(os.path.join(HEALTHY_ROOT, d))
    ]
    folders = sorted(folders)

    summary = {}
    last_result = {}
    all_failed = []

    for folder in folders:
        folder_path = os.path.join(HEALTHY_ROOT, folder)

        # اسم النبات فقط بدون healthy
        plant_name = clean_plant_name(folder)
        plant_name_safe = safe_name(plant_name)

        all_features, prototype, failed_images = process_single_plant_folder(
            folder_path=folder_path,
            plant_name=plant_name,
            seg_model=seg_model,
            cls_model=cls_model,
            cls_tf=cls_tf
        )

        all_failed.extend(failed_images)

        if all_features is None:
            print(f"[WARNING] No valid segmented healthy images for {plant_name}")

            summary[plant_name] = {
                "total_valid_features": 0,
                "feature_dim": 0,
                "all_features_file": None,
                "prototype_file": None,
                "prototype_saved": False,
                "failed_images": len(failed_images)
            }
            continue

        features_filename = f"{plant_name_safe}_all_features.npy"
        prototype_filename = f"{plant_name_safe}_prototype.npy"

        features_path = os.path.join(SAVE_DIR, features_filename)
        prototype_path = os.path.join(SAVE_DIR, prototype_filename)

        np.save(features_path, all_features)
        np.save(prototype_path, prototype)

        print(f"Saved features : {features_path} | shape={all_features.shape}")
        print(f"Saved prototype: {prototype_path} | shape={prototype.shape}")

        summary[plant_name] = {
            "total_valid_features": int(all_features.shape[0]),
            "feature_dim": int(all_features.shape[1]),
            "all_features_file": features_filename,
            "prototype_file": prototype_filename,
            "prototype_saved": True,
            "failed_images": len(failed_images)
        }

        last_result = {
            "plant_name": plant_name,
            "all_features_shape": list(all_features.shape),
            "prototype_shape": list(prototype.shape),
            "all_features_file": features_filename,
            "prototype_file": prototype_filename
        }

    summary_path = os.path.join(SAVE_DIR, "prototype_summary.json")
    last_result_path = os.path.join(SAVE_DIR, "last_prototype_inference_result.json")
    failed_path = os.path.join(SAVE_DIR, "failed_images.json")

    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    with open(last_result_path, "w", encoding="utf-8") as f:
        json.dump(last_result, f, ensure_ascii=False, indent=2)

    with open(failed_path, "w", encoding="utf-8") as f:
        json.dump(all_failed, f, ensure_ascii=False, indent=2)

    print("\n======================================")
    print("DONE")
    print(f"All outputs saved in: {SAVE_DIR}")
    print("======================================")


# =========================================================
# 9) RUN
# =========================================================
if __name__ == "__main__":
    build_prototypes_per_plant()